### ISSUE TITLE
Optional rendering using no markup.

### ISSUE THREAD

**Issue by mewmew** [slyrz/mango#3]
First of, thanks for a great tool! It fits perfectly with the `go generate` command.

It would be great if markup rendering was optional, specifically so that rendering issues caused by it can be mitigated. I tried to use `mango` to generate a man page for https://github.com/mewrev/ll2dot but unintentional markup (e.g. the presence of `*`) in the comments caused rendering issues. Notice that the text was cut short since the `.` after the second `*` in `*.ll` was placed on a new line and was thus treated as a man command rather than plain text.

```shell
mango ll2dot.go
```

Doc comment:
```go
// ll2dot is a tool which creates control flow graphs of LLVM IR assembly files
// (e.g. *.ll -> *.dot). The output is a set of GraphViz DOT files, each
// representing the control flow graph of a function using one node per basic
// block.
//
// For a source file "foo.ll" containing the functions "bar" and "baz" the
// following DOT files will be created:
//
//    foo_graphs/bar.dot
//    foo_graphs/baz.dot
package main
```

Output:
```man
.TH "LL2DOT" 1 "2015-02-12" "Ll2dot" "Ll2dot Manual"
.SH "NAME"
ll2dot is a tool which creates control flow graphs of LLVM IR assembly files
(e.g.
.B ".ll -> "
.dot). The output is a set of GraphViz DOT files, each
representing the control flow graph of a function using one node per basic
block.
.PP
For a source file "foo.ll" containing the functions "bar" and "baz" the
following DOT files will be created:
.PP
foo
graphs/bar.dot
foo
graphs/baz.dot
.PP
.SH "SYNOPSIS"
ll2dot
.I "[option...]"
.I "[argument...]"
.PP
.SH "OPTIONS"
.B "-f"
.RS 4
Force overwrite existing graph directories.
.RE
.PP
.B "-funcs"
<string>
.RS 4
Comma separated list of functions to parse (e.g. "foo,bar").
.RE
.PP
.B "-img"
.RS 4
Generate an image representation of the CFG.
.RE
.PP
.B "-q"
.RS 4
Suppress non-error messages.
.RE
.PP
```

* Incorrect rendering caused by unintentional markup.
![Incorrect rendering](https://i.imgur.com/NRXX2rp.png)

* Plain text rendering.
![Plain text rendering](https://i.imgur.com/l8dQGNz.png)

**Comment by slyrz** [comment]
Hi there, it's nice to hear that you like this tool. When I wrote it, I completely
missed that the markup might clash with the users comments. Your new plain command line flag is a nice way of avoiding such issues. Thanks!
